server {
    listen 80;
    root /usr/share/nginx/html;
    index kitchen.html;

    location / {
        try_files $uri $uri/ /kitchen.html;
    }

    location /api/ {
        include /etc/nginx/conf.d/api-proxy.conf;
        proxy_pass http://gateway:8000;
    }

    gzip on;
    gzip_types text/css application/javascript application/json;
}
